MyBlog/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('BlogApp.urls')),
    url(r'', include('CommentApp.urls')),
]

# 我们前面建立了一个 urls.py 文件，并且绑定了 URL 和视图函数 index，但是 django 并不知道。django 匹配 URL 模式是在 blogproject 目录（即 settings.py 文件所在的目录）的 urls.py 下的，所以我们要把 blog 应用下的 urls.py 文件包含到 blogproject\urls.py 里去
# include 前还有一个 ''，这是一个空字符串。这里也可以写其它字符串，django 会把这个字符串和后面 include 的 urls.py 文件中的 URL 拼接

CommentApp/models.py
# 评论的数据路模型
from django.db import models
from django.utils import timezone

# 评论(数据库都要继承models.Model类，里面元素调用model对象)
class Comment(models.Model):
    name = models.CharField('名字', max_length=50)
    email = models.EmailField('邮件')
    url = models.URLField('网址', blank=True)  # url可为空
    text = models.TextField('内容')
    create_time = models.DateTimeField('创建时间', default=timezone.now)
    # 一对多关联
    post = models.ForeignKey('BlogApp.Post', verbose_name='文章', on_delete=models.CASCADE)

    # 定义模型显示名字
    class Meta:
        verbose_name = '评论'
        verbose_name_plural = verbose_name
        # 内部类Meta能够指定能够指定一些属性的值来规定该模型具有的一些特性
        # ordering属性用来指定文章排序方式
        ordering = ['-create_time']

    def __str__(self):
        return '{}:{}'.format(self.name, self.text[:20])

templates/BlogShow/detail.html
{% extends 'base.html' %}
{%load comments_extras%}
{% block main %}
    <article class="post post-{{ post.pk }}">
        <header class="entry-header">
            <h1 class="entry-title">{{ post.title }}</h1>
            <div class="entry-meta">
                <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                <span class="post-date"><a href="#"><time class="entry-date"
                                                          datetime="{{ post.create_time }}">{{ post.create_time }}</time></a></span>
                <span class="post-author"><a href="#">{{ post.author }}</a></span>
                <span class="comments-link"><a href="#">4 评论</a></span>
                <span class="views-count"><a href="#">588 阅读</a></span>
            </div>
        </header>
        <div class="entry-content clearfix">
            {{ post.body|safe }}
        </div>
    </article>
    <section class="comment-area" id="comment-area">
        <hr>
        <h3>发表评论</h3>
        {%show_comments_form post%}
        <div class="comment-list-panel">
            {% show_comment post %}
        </div>
    </section>
{%endblock main%}
{% block toc %}
  {% if post.toc %}
    <div class="widget widget-content">
      <h3 class="widget-title">文章目录</h3>
      <div class="toc">
        <ul>
          {{ post.toc|safe }}
        </ul>
      </div>
    </div>
  {% endif %}
{% endblock toc %}

templates/BlogShow/index.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block main %}
    {%for post in post_list%}
        <article class="post post-{{post.pk}}">
            <header class="entry-header">
                <h1 class="entry-title">
                    <a href="{{post.get_absolute_url}}">{{post.title}}</a>
                </h1>
                <div class="entry-meta">
                    <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                    <span class="post-date"><a href="#"><time class="entry-date"
                                                              datetime="{{ post.create_time }}">{{ post.create_time}}</time></a></span>
                    <span class="post-author"><a href="#">{{ post.author }}</a></span>
                    <span class="comments-link"><a href="#">{{post.comment_set.count}} 评论</a></span>
                    <span class="views-count"><a href="#">588 阅读</a></span>
                </div>
            </header>
            <div class="entry-content clearfix">
                <p>{{ post.excerpt }}</p>
                <div class="read-more cl-effect-14">
                    <a href="{{ post.get_absolute_url}}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                </div>
            </div>
        </article>
    {% empty %}
          <div class="no-post">暂时还没有发布的文章！</div>
    {% endfor %}


    <!-- 简单分页效果
    <div class="pagination-simple">
        <a href="#">上一页</a>
        <span class="current">第 6 页 / 共 11 页</span>
        <a href="#">下一页</a>
    </div>
    -->
    <div class="pagination">
        <ul>
            <li><a href="">1</a></li>
            <li><a href="">...</a></li>
            <li><a href="">4</a></li>
            <li><a href="">5</a></li>
            <li class="current"><a href="">6</a></li>
            <li><a href="">7</a></li>
            <li><a href="">8</a></li>
            <li><a href="">...</a></li>
            <li><a href="">11</a></li>
        </ul>
    </div>
{% endblock main %}